### ISSUE TITLE
Find a solution for error handling

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#16]
From the `eve API` p.o.v, it will be difficult to add custom errors, so we need to handle standard HTTP errors.

I think the most efficient solution is to use a global error handling on each API requests and override the cases we know

---

Aesthetically what do you think ? I'm not a big fan of the popups à-la-`growl` but it's probably the easiest solution to integrate for the global design and able to handle multiple notifications

cc @cerisier @aimxhaisse

**Comment by cerisier** [comment]
Fine with me. I have a great notification service for Angular :smile:

**Comment by moul** [comment]
Ok perfect, so you're assigned :)

**Comment by aimxhaisse** [comment]
:ok_hand:
