### ISSUE TITLE
Make paths relatives

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#17]
I just released the "make build" result on http://pathwar.github.io/portal.pathwar.net/

And some js/css assets are fetched without the /portal.pathwar.net/ path prefix

We should use only relative paths for assets

**Comment by cerisier** [comment]
Actually its only the html base attribute that should be dynamic

**Comment by cerisier** [comment]
We can't make the paths relative. What we can do though is change the base attribute at gulp build time.
I can do this via an ENVIRONMENT variable if you want. Something like BASE_PATH.

**Comment by moul** [comment]
LGTM, let's go

**Comment by cerisier** [comment]
Paths are still absolutes.
Base only work for relative paths.
