### ISSUE TITLE
[META TOPIC] MVP

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#23]
This ticket will evolve with new ideas, when possible, we need to create a new ticket and a pull request per sub-tasks or at least be explicit in the commit message.

MVP sections : 
- [x] user login/register
- [x] levels

---

cc @cerisier, @aimxhaisse, @Solvik, @blotus, @mlequeux, @vikbez 
Do you have other ideas for the MVP ? if you have ideas for bonus, you can also list them so we have a place to read again when the MVP will be finished. So let's discuss here !

**Comment by aimxhaisse** [comment]
Random ideas, probably not for the MVP:
- per session global chatbox
- hall of fames of tricky levels with very little validations (maybe tag these levels as 'famable')
- list of contributions of a user (via github, linked with cool achievements)
- gravatar, links to external profiles (github, twitter, ...)
- http://is-{level}-down.{session}.pathwar.net?

**Comment by aimxhaisse** [comment]
- consider adding a service that visits a level once dumped, takes a screenshot, and pushes it to the portal (so on the level page we can have a preview of the level). Pros: cool, Cons: that can be used to know if a level is defaced or not.

**Comment by moul** [comment]
Thank you @aimxhaisse, just added your ideas on this issue: https://github.com/pathwar/api.pathwar.net/issues/4, I will create models as soon as possible even if we don't use them explicitly from the MVP launch

**Comment by cerisier** [comment]
Random Ideas, not for MVP.
- Tags for each level (Beginner, XSS, CSRF)
- Tags like XSS could link to definition page as a primer on content strategy like Digital Ocean
- "What you will learn" section on the level page
- Own set of icons
- Simpler Logo
- One level only breadcrumb: "Get Back" arrow appears at level n + 1.
- Organization-wide global points or progress
- Anything on Ethic ? Important as we give people weapons basically.
