### ISSUE TITLE
Handle login

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#30]
## first request
- method: `POST`
- path: `/user-tokens`
- headers: Basic AUTH for `{user}:{pass}`

You will receive a new user-token with an `expiry_date` set to NOW() + 1 hour
## next requests
- headers: Basic AUTH for `{token}:`

**Comment by moul** [comment]
Blocked by: https://github.com/pathwar/api.pathwar.net/issues/26

**Comment by cerisier** [comment]
Initial login done. Closing this.

**Comment by moul** [comment]
:ok_hand:
