### ISSUE TITLE
Flush cache on logout

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#40]
After clicking logout, even if you cannot make new API calls, the results of the old requests seems to be cached, even if we switch from a section to another

Can you flush cache on login or at least perform a page refresh ?

**Comment by cerisier** [comment]
I can't find a way to flush cache for this :disappointed: 
Will handle this issue by a client side permission check for all states.

**Comment by cerisier** [comment]
Closing as new issue created for this (See #45)
