### ISSUE TITLE
inclusion fichiers http(s)

### ISSUE THREAD

**Issue by Thiryn** [pathwar/portal.pathwar.net#89]
Si on accede au site en http, on a des erreurs de type

```
Font from origin 'https://portal.pathwar.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://portal.pathwar.net' is therefore not allowed access.
```

si on y accede en https 

```
Mixed Content: The page at 'https://portal.pathwar.net/#/login' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/services/feed/load?callback=angular.callbacks._0&num=10&q=http:%2F%2Fpathwar.tumblr.com%2Frss&v=1.0'. This request has been blocked; the content must be served over HTTPS.
```

;)

**Comment by moul** [comment]
Thanks for reporting :)

**Comment by aimxhaisse** [comment]
Same thing when accessing the page of a level, the preview iframe does not load:

Blocked loading mixed active content "http://login:token@73f7afe-58b3-4e4e-91bb-c34d2ffd1fc1.levels.pathwar.net/"

**Comment by moul** [comment]
We should add CORS headers on level proxy

**Comment by moul** [comment]
And also catch the iframe loading error to display a nice error and ask the user to open the website in an external tab instead of trying to open it in an iframe

**Comment by moul** [comment]
About the warnings when using the http version, it's very strange.

The related code is: https://github.com/pathwar/portal.pathwar.net/blob/master/app/organizations/views/view.tpl.jade#L29-L33

I checked the compiled version on production: https://portal.pathwar.net/templates.js:

``` html
<svg height="48" width="48" class="bg-lightest-gray rounded p1 ml1 mr1\">
  <use xlink:href="assets/icons/defs/svg/sprite.defs.svg#flash"></use>
</svg>
<svg height="48" width="48" class="bg-lightest-gray rounded p1 ml1 mr1">
  <use xlink:href="assets/icons/defs/svg/sprite.defs.svg#3d-glasses"></use>
</svg>
```

The code looks ok, but the browser keeps trying to get the assets from https, even with relative urls

Needing more investigation (cc @cerisier)

**Comment by Thiryn** [comment]
can't log in from https://portal.pathwar.net/#/login
with console error :

```
XMLHttpRequest cannot load https://api.pathwar.net/accounts/af7a7ef5-aa90-4e17-8662-002e12e0b1b7. The 'Access-Control-Allow-Origin' header has a value 'http://portal.pathwar.net' that is not equal to the supplied origin. Origin 'https://portal.pathwar.net' is therefore not allowed access.
```

**Comment by moul** [comment]
Just fixed the latest problem

So the only missing problem is about the strange one with SVG files.
I just tried it locally using the production api, so portal running locally with http:// scheme, but requests on https:// production API, and I don't have the problem
It seems to be specific to production portal

**Comment by moul** [comment]
there is still a problem for loading http levels in iframe from the https portal
