### ISSUE TITLE
Dynamic menu

### ISSUE THREAD

**Issue by cerisier** [pathwar/portal.pathwar.net#9]
Menu entries should be added dynamically by the modules

**Comment by moul** [comment]
Yep, but do not forget that all the resources are top-level on the API but not from a user point-of-view

i.e.:  user-tokens is related to a user-profile section and should be available from a dropdown menu on the profile or something like this

By adding dynamically the entries from the modules, are you able to choose in which menu the entries will be ?

Else, we can keep it manual, I think we should not get over 10 menu entries for the main menu

**Comment by cerisier** [comment]
Absolutely.
There will be one or more global menus like the main menu.
And each module can expose its own menu in which submodules can add entries.

**Comment by moul** [comment]
Perfect !

**Comment by cerisier** [comment]
I don't want to do that anymore
