### ISSUE TITLE
Add "validation message" examples

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#96]
![](https://www.dropbox.com/s/3r5o6771b83rvdc/Screenshot%202015-09-15%2009.21.11.png?dl=1)

On the right, i.e:
- `I used 'curl http://xxxx?yy=zzz'`
- `I uploaded a remote shell and I found the token in the /tmp folder`
- `I'm just lucky, manual bruteforce for 5 hours`

**Comment by sylvainkalache** [comment]
Or may be a grey text instead of "Enter your validation message here" or a ? icon with a simple explanation
